background = #080a12
foreground = #d8e4ef
cursor-color = #ffffff
selection-background = #25334b
selection-foreground = #ffffff

palette = 0=#080a12
palette = 1=#ff668c
palette = 2=#b6ff2e
palette = 3=#ecdc70
palette = 4=#527cff
palette = 5=#a875ef
palette = 6=#65e7ef
palette = 7=#d8e4ef
palette = 8=#59647b
palette = 9=#ff8eab
palette = 10=#d3ff7b
palette = 11=#fff19a
palette = 12=#8ba5ff
palette = 13=#cca5ff
palette = 14=#9efaff
palette = 15=#ffffff
