foreground #d8e4ef
background #080a12
selection_foreground #ffffff
selection_background #25334b

cursor #ffffff
cursor_text_color #080a12

active_border_color #b6ff2e
active_tab_background #b6ff2e

color0 #080a12
color1 #ff668c
color2 #b6ff2e
color3 #ecdc70
color4 #527cff
color5 #a875ef
color6 #65e7ef
color7 #d8e4ef
color8 #59647b
color9 #ff8eab
color10 #d3ff7b
color11 #fff19a
color12 #8ba5ff
color13 #cca5ff
color14 #9efaff
color15 #ffffff
